services:
  postgresql:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: diogo
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: diogo
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U diogo"]
      interval: 5s
      timeout: 5s
      retries: 5
  localstack:
    image: localstack/localstack
    platform: linux/arm64
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY: test
      AWS_SECRET_ACCESS_KEY: test
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    depends_on:
      postgresql:
        condition: service_healthy
      localstack:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql://diogo:123456@postgres:5432/diogo?schema=public
